CREATE DATABASE BD_FORNPROD_2E;

USE BD_FORNPROD_2E;

CREATE TABLE FORNECEDORES (
	ID_FORN INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	RAZAO_SOCIAL_FORN VARCHAR(60) UNIQUE NOT NULL, 
	CNPJ_FORN VARCHAR(14) UNIQUE NOT NULL,
	LOGRADOURO_FORN VARCHAR(60) NOT NULL,
	BAIRRO_FORN VARCHAR(30) NOT NULL,
	CIDADE_FORM VARCHAR(30) NOT NULL,
	UF_FORM VARCHAR(2) UNIQUE NOT NULL,
	CEP_FORM CHAR(8) NOT NULL
);

CREATE TABLE PRODUTOS (
	ID_PROD INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	DESC_PROD VARCHAR(60) UNIQUE NOT NULL,
	QTDE_PROD INT NOT NULL
);

CREATE TABLE FORN_PRODUTOS (
	ID_FORN INT UNSIGNED NOT NULL,
	ID_PROD INT UNSIGNED NOT NULL,
	FOREIGN KEY (ID_FORN) REFERENCES FORNECEDORES (ID_FORN),
	FOREIGN KEY (ID_PROD) REFERENCES PRODUTOS (ID_PROD)
);

ALTER TABLE PRODUTOS
ADD VALOR_UNITARIO DECIMAL(5,2) NOT NULL;

INSERT INTO PRODUTOS(DESC_PROD, QTDE_PROD, VALOR_UNITARIO)
VALUES
('Uva Itália kg', 1000, 9.90),
('Maçã Fuji kg', 800, 4.90),
('Limão Taiti kg', 1500, 2.90),
('Laranja kg', 3000, 3.90),
('Cebola kg', 1000, 2.50),
('Alface kg', 200, 1.99),
('Cenoura kg', 500, 3.90),
('Tomate kg', 300, 5.90),
('Couve un', 100, 2.90),
('Agrião un', 50, 3.90),
('Alho Pct', 400, 1.50),
('Banana Prata Dz', 50, 3.80);

SELECT * FROM PRODUTOS;
